### ISSUE TITLE
Repo Screenshot preview

### ISSUE THREAD

**Issue by Napiophelios** [mootpoint/church#2]
Wow, I am glad you liked my additions to the mod :)

you need to edit your Readme.md file
and link the preview image to your repo image:
https://raw.githubusercontent.com/mootpoint/cross/master/screenshot.png
That way nothing happens if mine gets deleted/changed.

Also, you deleted your screenshots when you did the merge
so your forum topic now has no image preview  :(

**Comment by mootpoint** [comment]
oh crap im sorry, will fix that now

**Comment by mootpoint** [comment]
done and closed
