### ISSUE TITLE
thinking about making this a church modpack

### ISSUE THREAD

**Issue by mootpoint** [mootpoint/church#3]
to add : 
   * pews
   * stained glass
   * bells
   * a podium or altar maybe both
   * candles

with this make this into one church mod or a modpack with various church things

**Comment by mootpoint** [comment]
@Napiophelios what do you think?

**Comment by mootpoint** [comment]
pews added

**Comment by Napiophelios** [comment]
pews added...ah man you messed up the trinity.
you know how hard it was to get it to 333 lines of code
-JK

I would make it a mod pack.
that way users can pick and choose which things to include in their game
without having to edit any code out if there is something they don't wanna use.

**Comment by mootpoint** [comment]
All right I renamed the master directory what should three cross /
graveyard be called?
Or should these be split into two 'mods' inside the mod pack add in customizable grave markers with names like signs, also one small rectangle plot marker

**Comment by mootpoint** [comment]
this mods has been restructured as a modpack

**Comment by mootpoint** [comment]
split grave and cross into seperate mod, together in modpack

**Comment by mootpoint** [comment]
Closing this to open a different issue for each idea
