### ISSUE TITLE
pews/podiums - missing aspen wood

### ISSUE THREAD

**Issue by Napiophelios** [mootpoint/church#4]
![screenshot](https://cloud.githubusercontent.com/assets/8119411/21224553/b4b04fa6-c29a-11e6-92d2-d400efe4ba73.png)

I am working on getting all 3 sections of the pews to set at the same time,
so that you only have one inventory item per material type.

but it only works if you are facing north...err
https://youtu.be/XoO358oADWo   (approx. 1min video)

I also experimented with right-click to sit for each section..that working okay
but when player right-click to get up he falls into node and have to jump to move away.

**Comment by mootpoint** [comment]
for the sit function take a look at homedecor chairs

**Comment by mootpoint** [comment]
if you get it working let me know we will add it in

**Comment by mootpoint** [comment]
@Napiophelios can you post the code for this on github?

**Comment by Napiophelios** [comment]
Yeah, but mine are registered completely different than yours. 
I used a cookie cutter code to register the nodes;
I didnt like how your registration presents the nodes in creative inv.
No offense, I just am a little OCD.  :)

**Comment by mootpoint** [comment]
No offense taken, I am planning on fixing that, cause I don't like it
either. I am very used to working with people with ocd :) seriously it is
my career, I am always open to suggestions, if you find a better way to do
something, make a pull request! I am still learning and haven't known lua
long. I am always interested in seeing how others do things.

**Comment by Napiophelios** [comment]
All right its up. The ini file with "WIP" in the name is the one with 
the botched "auto" placement and the quirky sit function.

https://github.com/Napiophelios/church_pews

**Comment by mootpoint** [comment]
alright cool, i sent you an invite to be a collaborator on the church mod, that way you can make pull requests and the like

**Comment by Napiophelios** [comment]
nice.

**Comment by mootpoint** [comment]
I DID IT I DID IT!!!!!! i got the pews orientated right, give me a moment i will add it in

**Comment by mootpoint** [comment]
well i need a break so give me five

**Comment by mootpoint** [comment]
sit function fixed as well

**Comment by mootpoint** [comment]
Closing this issue everything is fixed now
